import * as vscode from 'vscode';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { WorktreeConfig } from './config';
import { log } from './log';

// We never touch the user's own `.env` (it is often tracked and may hold secrets).
// Instead we own a dedicated, git-excluded file and document pointing debug/task
// `envFile` settings at it.
export const ENV_FILE = '.env.worktree';

export interface EnvVars {
  branch: string;
  color: string;
}

/**
 * Injects vars into integrated terminals (EnvironmentVariableCollection) and,
 * when enabled, writes the owned `.env.worktree`. Returns the relative path written
 * (for the caller to git-exclude), or undefined if no file was written.
 */
export async function applyEnv(
  ctx: vscode.ExtensionContext,
  folder: vscode.WorkspaceFolder,
  cfg: WorktreeConfig,
  vars: EnvVars,
): Promise<string | undefined> {
  if (cfg.injectEnv) {
    const col = ctx.environmentVariableCollection;
    col.clear();
    col.persistent = false; // recomputed every activation, so never goes stale
    col.description = 'Worktree Helper: branch + titlebar color';
    col.replace(cfg.branchEnvVar, vars.branch);
    col.replace(cfg.colorEnvVar, vars.color);
  }

  if (cfg.writeEnvFile) {
    const body =
      `# Generated by Worktree Helper — git-excluded, safe to delete.\n` +
      `${cfg.branchEnvVar}=${vars.branch}\n` +
      `${cfg.colorEnvVar}=${vars.color}\n`;
    try {
      await fs.writeFile(path.join(folder.uri.fsPath, ENV_FILE), body, 'utf8');
      return ENV_FILE;
    } catch (e) {
      log(`Failed to write ${ENV_FILE}: ${String(e)}`);
    }
  }
  return undefined;
}

/** Clears injected terminal vars and removes the owned env file. */
export async function clearEnv(ctx: vscode.ExtensionContext, folder: vscode.WorkspaceFolder): Promise<void> {
  ctx.environmentVariableCollection.clear();
  try {
    await fs.unlink(path.join(folder.uri.fsPath, ENV_FILE));
  } catch {
    // already gone
  }
}
